trigger:
- main

pool:
  name: macOS-Agent-Pool

variables:
  AZURE_SUBSCRIPTION: 'Azure-Terraform-Connection'

stages:
- stage: Terraform
  displayName: 'Terraform Infrastructure Deployment'
  jobs:
  - job: Terraform
    steps:

    # Install Terraform Manually (if TerraformInstaller@0 is not available)
    - script: |
        echo "Installing Terraform using Homebrew..."
        brew update
        brew install terraform
      displayName: 'Install Terraform on macOS'

    # Authenticate with Azure
    - task: AzureCLI@2
      displayName: "Azure Login (Service Principal)"
      inputs:
        connectedServiceNameARM: $(AZURE_SUBSCRIPTION)  # Add this line
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          az login --service-principal --username "$(ARM_CLIENT_ID)" --password "$(ARM_CLIENT_SECRET)" --tenant "$(ARM_TENANT_ID)"
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    # Initialize Terraform
    - script: terraform init
      displayName: 'Terraform Init'

    # Terraform Plan
    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    # Terraform Apply
    - script: terraform apply -auto-approve
      displayName: 'Terraform Apply'

